repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: trailing-whitespace
        args: ['--markdown-linebreak-ext=md,markdown']
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/zmoon/findent-pre-commit
    rev: "17b1b07"
    hooks:
      - id: findent-pypi
        additional_dependencies: [findent==4.3.1]
        args: ['-i3']
        exclude: |
            (?x)^(
                src/core/charpak_mod\.F90|
                src/core/qfyaml_mod\.F90|
                src/process/old/.*\.F90|
                src/process/Process_driver_template.F90|
                drivers/ccpp/.*\.F90|
                parameters/.*\.F90|
                src/external/GOCART/.*
            )$

  - repo: https://github.com/BlankSpruce/gersemi
    rev: "0.18.1"
    hooks:
      - id: gersemi
        args: [--in-place, --indent=2]
        exclude: (?x)^(
            cmake/FindNetCDF.cmake
          )$

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        exclude: |
            (?x)^(
                src/process/old/.*\.F90|
                drivers/ccpp/.*\.F90|
                parameters/.*\.F90|
                src/external/GOCART/.*
            )$
