version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-22.9"
  jobs:
    pre_build:
      - cd docs && doxygen Doxyfile
      - cd docs && doxysphinx build . $READTHEDOCS_OUTPUT/html/ Doxyfile

sphinx:
  configuration: docs/conf.py

conda:
  environment: docs/environment-docs.yml
