# Conda environment for building the CATChem docs
name: catchem-docs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  #
  # Docs
  - sphinx=8.*
  - sphinx-autobuild
  - sphinx-design
  - sphinx-book-theme
  - sphinx_rtd_theme
  - sphinx-togglebutton
