name: Doxygen docs

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
permissions:
  contents: write

jobs:
  doxygen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y doxygen graphviz

      - name: Build
        run: |
          cd docs2
          doxygen
          cd -

      - name: Deploy
        if: github.ref == 'refs/heads/develop'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs2/html
          git-config-name: github-actions
          git-config-email: 41898282+github-actions[bot]@users.noreply.github.com
          clean: true
          clean-exclude: .nojekyll
